//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDConfig {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDConfig.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read analog value failed. 的本地化字符串。
        /// </summary>
        internal static string Get_ADC_Failed {
            get {
                return ResourceManager.GetString("Get_ADC_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid file format. 的本地化字符串。
        /// </summary>
        internal static string Invalid_File_Format {
            get {
                return ResourceManager.GetString("Invalid_File_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read OSD done. 的本地化字符串。
        /// </summary>
        internal static string Read_OSD_Done {
            get {
                return ResourceManager.GetString("Read_OSD_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read OSD failed. 的本地化字符串。
        /// </summary>
        internal static string Read_OSD_Failed {
            get {
                return ResourceManager.GetString("Read_OSD_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong Data Version. 的本地化字符串。
        /// </summary>
        internal static string Read_OSD_Wrong_Ver {
            get {
                return ResourceManager.GetString("Read_OSD_Wrong_Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read setting failed. 的本地化字符串。
        /// </summary>
        internal static string Read_Setting_Failed {
            get {
                return ResourceManager.GetString("Read_Setting_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save setting failed. 的本地化字符串。
        /// </summary>
        internal static string Save_Setting_Failed {
            get {
                return ResourceManager.GetString("Save_Setting_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload charset done. 的本地化字符串。
        /// </summary>
        internal static string Upload_CharSet_Done {
            get {
                return ResourceManager.GetString("Upload_CharSet_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload charset failed. 的本地化字符串。
        /// </summary>
        internal static string Upload_CharSet_Failed {
            get {
                return ResourceManager.GetString("Upload_CharSet_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading 的本地化字符串。
        /// </summary>
        internal static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write OSD done. 的本地化字符串。
        /// </summary>
        internal static string Write_OSD_Done {
            get {
                return ResourceManager.GetString("Write_OSD_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write OSD failed. 的本地化字符串。
        /// </summary>
        internal static string Write_OSD_Failed {
            get {
                return ResourceManager.GetString("Write_OSD_Failed", resourceCulture);
            }
        }
    }
}
