//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.261
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDConfig {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OSDItemNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OSDItemNames() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDConfig.OSDItemNames", typeof(OSDItemNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Altitude (Absolute) 的本地化字符串。
        /// </summary>
        internal static string Alt {
            get {
                return ResourceManager.GetString("Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Altitude (Relative) 的本地化字符串。
        /// </summary>
        internal static string Alt_R {
            get {
                return ResourceManager.GetString("Alt_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Voltage A 的本地化字符串。
        /// </summary>
        internal static string BatA {
            get {
                return ResourceManager.GetString("BatA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Voltage A (AD) 的本地化字符串。
        /// </summary>
        internal static string BatA_ADC {
            get {
                return ResourceManager.GetString("BatA_ADC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Voltage B 的本地化字符串。
        /// </summary>
        internal static string BatB {
            get {
                return ResourceManager.GetString("BatB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Voltage B (AD) 的本地化字符串。
        /// </summary>
        internal static string BatB_ADC {
            get {
                return ResourceManager.GetString("BatB_ADC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center 的本地化字符串。
        /// </summary>
        internal static string Cen {
            get {
                return ResourceManager.GetString("Cen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current A 的本地化字符串。
        /// </summary>
        internal static string CurA {
            get {
                return ResourceManager.GetString("CurA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current A (AD) 的本地化字符串。
        /// </summary>
        internal static string CurA_ADC {
            get {
                return ResourceManager.GetString("CurA_ADC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current B 的本地化字符串。
        /// </summary>
        internal static string CurB {
            get {
                return ResourceManager.GetString("CurB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current B (AD) 的本地化字符串。
        /// </summary>
        internal static string CurB_ADC {
            get {
                return ResourceManager.GetString("CurB_ADC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flight Mode 的本地化字符串。
        /// </summary>
        internal static string FMod {
            get {
                return ResourceManager.GetString("FMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPS Lock 的本地化字符串。
        /// </summary>
        internal static string GPL {
            get {
                return ResourceManager.GetString("GPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPS Coord 的本地化字符串。
        /// </summary>
        internal static string GPS {
            get {
                return ResourceManager.GetString("GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visible Sats 的本地化字符串。
        /// </summary>
        internal static string GPSats {
            get {
                return ResourceManager.GetString("GPSats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home Direction 的本地化字符串。
        /// </summary>
        internal static string HDir {
            get {
                return ResourceManager.GetString("HDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home Distance 的本地化字符串。
        /// </summary>
        internal static string HDis {
            get {
                return ResourceManager.GetString("HDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heading 的本地化字符串。
        /// </summary>
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizon 的本地化字符串。
        /// </summary>
        internal static string Hor {
            get {
                return ResourceManager.GetString("Hor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heat Beat 的本地化字符串。
        /// </summary>
        internal static string MavB {
            get {
                return ResourceManager.GetString("MavB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pitch 的本地化字符串。
        /// </summary>
        internal static string Pit {
            get {
                return ResourceManager.GetString("Pit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Roll 的本地化字符串。
        /// </summary>
        internal static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heading Rose 的本地化字符串。
        /// </summary>
        internal static string Rose {
            get {
                return ResourceManager.GetString("Rose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RSSI 的本地化字符串。
        /// </summary>
        internal static string RSSI {
            get {
                return ResourceManager.GetString("RSSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RSSI (AD) 的本地化字符串。
        /// </summary>
        internal static string RSSI_ADC {
            get {
                return ResourceManager.GetString("RSSI_ADC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Status 的本地化字符串。
        /// </summary>
        internal static string SYS {
            get {
                return ResourceManager.GetString("SYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Throttle 的本地化字符串。
        /// </summary>
        internal static string Thr {
            get {
                return ResourceManager.GetString("Thr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Velocity 的本地化字符串。
        /// </summary>
        internal static string Vel {
            get {
                return ResourceManager.GetString("Vel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waypoint Direction 的本地化字符串。
        /// </summary>
        internal static string WDir {
            get {
                return ResourceManager.GetString("WDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waypoint Distance 的本地化字符串。
        /// </summary>
        internal static string WDis {
            get {
                return ResourceManager.GetString("WDis", resourceCulture);
            }
        }
    }
}
